# Generated by Django 3.1 on 2022-02-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product_category',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='product_value',
            new_name='variation_value',
        ),
    ]
